os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

language:
  - python

python:
  - "3.6"


install:
  - pip install -r requirements.txt

script:
  - python -m compileall ./GLaDOS.py
  - python -m compileall ./addons/*.py

cache:
  - pip

notifications:
  email:
    - false
